name: patient
description: "patient web reservation portal"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  go_router: ^15.0.0
  http: ^1.2.1
  uuid: ^4.4.0
  intl: any 
  equatable: ^2.0.5
  email_validator: ^3.0.0
  # appwrite: ^12.0.4 
  # flutter_easyloading: ^3.0.5 
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  # arabic_numbers: ^1.0.0
  pocketbase: ^0.22.0
  flutter_rating_stars: ^1.1.0
  proklinik_models:
    git:
      url: https://github.com/pheonixeye/proklinik_models.git
      ref: master
  meta_seo: ^3.0.9
  flutter_schema_org: ^1.0.0
  # proklinik_models:
  #   path: ../proklinik_models
      


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_lorem: ^2.0.0


flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/json/
    - assets/images/speciality_row/
    - assets/images/doc_avatars/
    - assets/images/offers_row/
    - assets/images/icons_svg/
    - assets/fonts/
    - assets/fonts/IBM/
    - assets/lang/


  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBM/font-Thin-100.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/IBM/font-ExtraLight-200.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/IBM/font-Light-300.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/IBM/font-Regular-400.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/IBM/font-Medium-500.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/IBM/font-SemiBold-600.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/IBM/font-Bold-700.ttf
          style: normal
          weight: 700
